github: [ZurrBot, ZurrBot] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: ZurrBot # Replace with a single Patreon username
ko_fi: Zurr_Md # Replace with a single Ko-fi username
custom: ['https://saweria.co/ZurrMD'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
